### ISSUE TITLE
Measurement Quality evaluation

### ISSUE THREAD

**Issue by capsizingHR** [ISAAKiel/statuAAR#1]
We have to discuss how to define and find outlier in the calculated body height values:
- propably check deviations of measurements -> maybe directly in the input part
- also in the input: check for multiple values for the same bone on the same individuum
- check deviations of calculated values -> how to work with few values? Quantiles? Std? something different?

**Comment by chrinne** [comment]
done: 
- readuserdata.R creates a df agg_measures with statistics for each measure
- checks for multiple individuals and measures but not for the bones or laterality
