### ISSUE TITLE
utils::fix-error

### ISSUE THREAD

**Issue by nmueller18** [ISAAKiel/statuAAR#11]
In `readuserdata.R` line 61, on Mac 10.13.6, R 4.0.3., `fix(measures.list)` leads to the following error:

`Fehler in .External2(C_dataentry, datalist, modes) : 
  unable to start data editor`

It seems Mac-related but similar error-messages in threads at stackoverflow do not help to solve it (X11 is installed, for example). Changing 'fix' to 'return' resolves this issue.
The question is: Is this functionality really needed?

**Comment by chrinne** [comment]
removed this option to open the data.frame driectly for edits. Now a error indicates to edit the data.frame of corresponding measure names.
